name: Build and Push Docker image to Docker Hub

on: 
  push:
    branches: ['alpine']
    
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: 3.10.8-alpine
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: rahulrrao/yadlts:latest
